<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-TAVNIOO" failures="1" tests="6" name="UI Automation Test Ecommerce" time="184.989" errors="0" timestamp="2025-09-13T13:04:00 IST">
  <testcase classname="ui.tests.ecommerce.InvalidLoginTest" name="loginInvalid" time="4.203"/>
  <testcase classname="ui.tests.ecommerce.LoginTest" name="login" time="30.432">
    <skipped/>
  </testcase> <!-- login -->
  <testcase classname="ui.tests.ecommerce.LoginTest" name="login" time="5.331"/>
  <testcase classname="ui.tests.ecommerce.ProductSearchTest" name="searchElementTest" time="2.826"/>
  <testcase classname="ui.tests.ecommerce.LoginTest" name="login" time="5.297">
    <skipped/>
  </testcase> <!-- login -->
  <testcase classname="ui.tests.ecommerce.LoginTest" name="login" time="7.022">
    <failure type="java.lang.AssertionError" message="expected [Adi boss] but found [Jatin Sharma]">
      <![CDATA[java.lang.AssertionError: expected [Adi boss] but found [Jatin Sharma]
at ui.tests.ecommerce.LoginTest.login(LoginTest.java:15)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- UI Automation Test Ecommerce -->
