<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-TAVNIOO" failures="1" tests="5" name="UI Automation Test Ecommerce" time="207.229" errors="0" timestamp="2025-08-28T15:48:13 IST">
  <testcase classname="ui.tests.ecommerce.LoginTest" name="login" time="5.272"/>
  <testcase classname="ui.tests.ecommerce.LoginTest" name="login" time="5.493">
    <skipped/>
  </testcase> <!-- login -->
  <testcase classname="ui.tests.ecommerce.LoginTest" name="login" time="4.484">
    <skipped/>
  </testcase> <!-- login -->
  <testcase classname="ui.tests.ecommerce.LoginTest" name="login" time="4.734">
    <skipped/>
  </testcase> <!-- login -->
  <testcase classname="ui.tests.ecommerce.LoginTest" name="login" time="3.759">
    <failure type="java.lang.AssertionError" message="expected [Adi boss] but found [Jatin Sharma]">
      <![CDATA[java.lang.AssertionError: expected [Adi boss] but found [Jatin Sharma]
at ui.tests.ecommerce.LoginTest.login(LoginTest.java:15)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- UI Automation Test Ecommerce -->
